/** Short, user-triggered Web Audio cues for Mio. No files or network needed. */

export type MioSfxCue = 'boop' | 'starlight' | 'quiet' | 'explore';

interface Tone {
	frequency: number;
	offsetMs: number;
	durationMs: number;
	gain: number;
	wave: OscillatorType;
}

export const MIO_SFX_RECIPES: Record< MioSfxCue, readonly Tone[] > = {
	boop: [
		{ frequency: 660, offsetMs: 0, durationMs: 45, gain: 0.045, wave: 'square' },
		{ frequency: 880, offsetMs: 55, durationMs: 70, gain: 0.04, wave: 'triangle' },
	],
	starlight: [
		{ frequency: 523, offsetMs: 0, durationMs: 55, gain: 0.045, wave: 'triangle' },
		{ frequency: 659, offsetMs: 55, durationMs: 55, gain: 0.04, wave: 'square' },
		{ frequency: 784, offsetMs: 110, durationMs: 90, gain: 0.045, wave: 'triangle' },
	],
	quiet: [
		{ frequency: 294, offsetMs: 0, durationMs: 95, gain: 0.035, wave: 'triangle' },
	],
	explore: [
		{ frequency: 392, offsetMs: 0, durationMs: 45, gain: 0.04, wave: 'square' },
		{ frequency: 587, offsetMs: 65, durationMs: 55, gain: 0.04, wave: 'square' },
		{ frequency: 784, offsetMs: 130, durationMs: 80, gain: 0.045, wave: 'triangle' },
	],
};

type AudioContextConstructor = new () => AudioContext;

interface Voice {
	oscillator: OscillatorNode;
	gain: GainNode;
}

const CARE_COOLDOWN_MS = 280;
const BOOP_COOLDOWN_MS = 180;
const BUCKET_WINDOW_MS = 2_000;
const BUCKET_LIMIT = 4;

export class MioSfx {
	private context: AudioContext | null = null;
	private voices = new Set< Voice >();
	private lastCueAt = new Map< MioSfxCue, number >();
	private acceptedAt: number[] = [];
	private reducedMotion: MediaQueryList | null = null;
	private enabled: boolean;
	private destroyed = false;
	private activePriority = 0;

	constructor( enabled: boolean ) {
		this.enabled = enabled;
		try {
			this.reducedMotion = window.matchMedia(
				'(prefers-reduced-motion: reduce)',
			);
		} catch {
			this.reducedMotion = null;
		}
	}

	isEnabled(): boolean {
		return this.enabled;
	}

	setEnabled( enabled: boolean ): void {
		this.enabled = enabled;
		if ( ! enabled ) {
			this.cancel();
		}
	}

	/** Play only from the trusted click generated by a native Mio button. */
	play( cue: MioSfxCue, trusted: boolean ): void {
		if (
			this.destroyed ||
			! this.enabled ||
			! trusted ||
			document.hidden
		) {
			return;
		}

		const nowMs = performance.now();
		const cooldown = cue === 'boop' ? BOOP_COOLDOWN_MS : CARE_COOLDOWN_MS;
		if ( nowMs - ( this.lastCueAt.get( cue ) ?? -Infinity ) < cooldown ) {
			return;
		}
		this.acceptedAt = this.acceptedAt.filter(
			( accepted ) => nowMs - accepted < BUCKET_WINDOW_MS,
		);
		if ( this.acceptedAt.length >= BUCKET_LIMIT ) {
			return;
		}

		const priority = cue === 'boop' ? 10 : 20;
		if ( this.voices.size > 0 && priority < this.activePriority ) {
			return;
		}
		if ( this.voices.size > 0 ) {
			this.cancel();
		}

		const context = this.ensureContext();
		if ( ! context ) {
			return;
		}
		if ( context.state === 'suspended' ) {
			void context.resume().catch( () => undefined );
		}

		this.lastCueAt.set( cue, nowMs );
		this.acceptedAt.push( nowMs );
		this.activePriority = priority;
		const recipe = this.reducedMotion?.matches
			? [ reducedTone( MIO_SFX_RECIPES[ cue ][ 0 ] ) ]
			: MIO_SFX_RECIPES[ cue ];
		for ( const tone of recipe ) {
			this.scheduleTone( context, tone );
		}
	}

	suspend(): void {
		this.cancel();
		if ( this.context?.state === 'running' ) {
			void this.context.suspend().catch( () => undefined );
		}
	}

	dispose(): void {
		if ( this.destroyed ) {
			return;
		}
		this.destroyed = true;
		this.cancel();
		const context = this.context;
		this.context = null;
		if ( context && context.state !== 'closed' ) {
			void context.close().catch( () => undefined );
		}
		this.lastCueAt.clear();
		this.acceptedAt = [];
	}

	private ensureContext(): AudioContext | null {
		if ( this.context ) {
			return this.context;
		}
		const AudioImpl: AudioContextConstructor | undefined =
			window.AudioContext ||
			( window as unknown as { webkitAudioContext?: AudioContextConstructor } )
				.webkitAudioContext;
		if ( ! AudioImpl ) {
			return null;
		}
		try {
			this.context = new AudioImpl();
		} catch {
			this.context = null;
		}
		return this.context;
	}

	private scheduleTone( context: AudioContext, tone: Tone ): void {
		const oscillator = context.createOscillator();
		const gain = context.createGain();
		const start = context.currentTime + tone.offsetMs / 1_000;
		const end = start + tone.durationMs / 1_000;
		const release = Math.min( 0.02, tone.durationMs / 2_000 );

		oscillator.type = tone.wave;
		oscillator.frequency.setValueAtTime( tone.frequency, start );
		gain.gain.setValueAtTime( 0.0001, start );
		gain.gain.linearRampToValueAtTime( tone.gain, start + 0.005 );
		gain.gain.setValueAtTime( tone.gain, Math.max( start + 0.005, end - release ) );
		gain.gain.exponentialRampToValueAtTime( 0.0001, end );
		oscillator.connect( gain );
		gain.connect( context.destination );

		const voice: Voice = { oscillator, gain };
		this.voices.add( voice );
		oscillator.addEventListener( 'ended', () => {
			this.voices.delete( voice );
			oscillator.disconnect();
			gain.disconnect();
			if ( this.voices.size === 0 ) {
				this.activePriority = 0;
			}
		}, { once: true } );
		oscillator.start( start );
		oscillator.stop( end + 0.005 );
	}

	private cancel(): void {
		const now = this.context?.currentTime ?? 0;
		for ( const voice of this.voices ) {
			try {
				voice.gain.gain.cancelScheduledValues( now );
				voice.gain.gain.setValueAtTime( 0.0001, now );
				voice.oscillator.stop( now + 0.001 );
			} catch {
				// A voice may already have ended between iteration and stop().
			}
		}
		this.voices.clear();
		this.activePriority = 0;
	}
}

function reducedTone( tone: Tone ): Tone {
	return {
		...tone,
		offsetMs: 0,
		durationMs: Math.min( 80, tone.durationMs ),
		gain: Math.min( 0.035, tone.gain ),
		wave: 'triangle',
	};
}
